import { PlayerPool } from '../services/stats.service';

export const mockPlayerPool: PlayerPool = {
  qbs: [
    {
      id: '1',
      name: 'Patrick Mahomes',
      position: 'QB',
      season: 2020,
      team: 'KC',
      fantasy_points: 400,
      games_played: 16,
    },
    {
      id: '2',
      name: 'Josh Allen',
      position: 'QB',
      season: 2020,
      team: 'BUF',
      fantasy_points: 350,
      games_played: 16,
    },
    {
      id: '3',
      name: 'Lamar Jackson',
      position: 'QB',
      season: 2020,
      team: 'BAL',
      fantasy_points: 300,
      games_played: 16,
    },
    {
      id: '4',
      name: 'Aaron Rodgers',
      position: 'QB',
      season: 2020,
      team: 'GB',
      fantasy_points: 250,
      games_played: 16,
    },
    {
      id: '5',
      name: 'Russell Wilson',
      position: 'QB',
      season: 2020,
      team: 'SEA',
      fantasy_points: 200,
      games_played: 16,
    },
  ],
  rbs: [
    {
      id: '6',
      name: 'Christian McCaffrey',
      position: 'RB',
      season: 2020,
      team: 'CAR',
      fantasy_points: 400,
      games_played: 16,
    },
    {
      id: '7',
      name: 'Dalvin Cook',
      position: 'RB',
      season: 2020,
      team: 'MIN',
      fantasy_points: 350,
      games_played: 16,
    },
    {
      id: '8',
      name: 'Alvin Kamara',
      position: 'RB',
      season: 2020,
      team: 'NO',
      fantasy_points: 300,
      games_played: 16,
    },
    {
      id: '9',
      name: 'Derrick Henry',
      position: 'RB',
      season: 2020,
      team: 'TEN',
      fantasy_points: 250,
      games_played: 16,
    },
    {
      id: '10',
      name: 'Aaron Jones',
      position: 'RB',
      season: 2020,
      team: 'GB',
      fantasy_points: 200,
      games_played: 16,
    },
    {
      id: '21',
      name: 'Ezekiel Elliott',
      position: 'RB',
      season: 2020,
      team: 'DAL',
      fantasy_points: 150,
      games_played: 16,
    },
    {
      id: '22',
      name: 'Nick Chubb',
      position: 'RB',
      season: 2020,
      team: 'CLE',
      fantasy_points: 100,
      games_played: 16,
    },
    {
      id: '23',
      name: 'Jonathan Taylor',
      position: 'RB',
      season: 2020,
      team: 'IND',
      fantasy_points: 50,
      games_played: 16,
    },
    {
      id: '24',
      name: 'James Robinson',
      position: 'RB',
      season: 2020,
      team: 'JAX',
      fantasy_points: 25,
      games_played: 16,
    },
    {
      id: '25',
      name: 'David Montgomery',
      position: 'RB',
      season: 2020,
      team: 'CHI',
      fantasy_points: 10,
      games_played: 16,
    },
  ],
  wrs: [
    {
      id: '11',
      name: 'Davante Adams',
      position: 'WR',
      season: 2020,
      team: 'GB',
      fantasy_points: 400,
      games_played: 16,
    },
    {
      id: '12',
      name: 'Tyreek Hill',
      position: 'WR',
      season: 2020,
      team: 'KC',
      fantasy_points: 350,
      games_played: 16,
    },
    {
      id: '13',
      name: 'Stefon Diggs',
      position: 'WR',
      season: 2020,
      team: 'BUF',
      fantasy_points: 300,
      games_played: 16,
    },
    {
      id: '14',
      name: 'DeAndre Hopkins',
      position: 'WR',
      season: 2020,
      team: 'ARI',
      fantasy_points: 250,
      games_played: 16,
    },
    {
      id: '15',
      name: 'Calvin Ridley',
      position: 'WR',
      season: 2020,
      team: 'ATL',
      fantasy_points: 200,
      games_played: 16,
    },
    {
      id: '26',
      name: 'Allen Robinson',
      position: 'WR',
      season: 2020,
      team: 'CHI',
      fantasy_points: 150,
      games_played: 16,
    },
    {
      id: '27',
      name: 'D.K. Metcalf',
      position: 'WR',
      season: 2020,
      team: 'SEA',
      fantasy_points: 100,
      games_played: 16,
    },
    {
      id: '28',
      name: 'A.J. Brown',
      position: 'WR',
      season: 2020,
      team: 'TEN',
      fantasy_points: 50,
      games_played: 16,
    },
    {
      id: '29',
      name: 'Mike Evans',
      position: 'WR',
      season: 2020,
      team: 'TB',
      fantasy_points: 25,
      games_played: 16,
    },
    {
      id: '30',
      name: 'Keenan Allen',
      position: 'WR',
      season: 2020,
      team: 'LAC',
      fantasy_points: 10,
      games_played: 16,
    },
    {
      id: '31',
      name: 'Terry McLaurin',
      position: 'WR',
      season: 2020,
      team: 'WAS',
      fantasy_points: 5,
      games_played: 16,
    },
  ],
  tes: [
    {
      id: '16',
      name: 'Travis Kelce',
      position: 'TE',
      season: 2020,
      team: 'KC',
      fantasy_points: 400,
      games_played: 16,
    },
    {
      id: '17',
      name: 'Darren Waller',
      position: 'TE',
      season: 2020,
      team: 'LV',
      fantasy_points: 350,
      games_played: 16,
    },
    {
      id: '18',
      name: 'George Kittle',
      position: 'TE',
      season: 2020,
      team: 'SF',
      fantasy_points: 300,
      games_played: 16,
    },
    {
      id: '19',
      name: 'Mark Andrews',
      position: 'TE',
      season: 2020,
      team: 'BAL',
      fantasy_points: 250,
      games_played: 16,
    },
    {
      id: '20',
      name: 'T.J. Hockenson',
      position: 'TE',
      season: 2020,
      team: 'DET',
      fantasy_points: 200,
      games_played: 16,
    },
  ],
};
